---
- name: Prepare
  hosts: all
  become: yes
  vars:
    php_packages:
      - php
      - php-cli
      - php-pdo
      - php-gd
      # - php-pdo_mysql
      - php-mysqli
      - php-opcache
      - php-mbstring
      - php-tidy
      - php-intl
      - php-zip
      - php-xml
      - php-dom
      - php-curl
    php_version: '7.4'
    php_default_version_debian: "7.4"
    php_opcache_enable_cli: "1"
  roles:
    - role: php-versions
    - role: php
    - role: composer
    - role: git
  pre_tasks:
    - name: install packages
      apt:
        name: dirmngr
        state: present
        update_cache: true
