---
name: Galaxy import

on:
  push:
    branches:
      - develop
      - master
  release:
    types:
      - published

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
