---
name: Molecule test
on:
  push:
    paths:
      - defaults/**
      - handlers/**
      - meta/**
      - molecule/**
      - tasks/**
      - templates/**
      - vars/**
      - .github/workflows/molecule.yml
    branches:
      - develop
      - master
  pull_request:
    paths:
      - defaults/**
      - handlers/**
      - meta/**
      - molecule/**
      - tasks/**
      - templates/**
      - vars/**
      - .github/workflows/molecule.yml
    branches:
      - develop
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: run molecule
        uses: gofrolist/molecule-action@v2

      # - name: Install test dependencies.
      #   run: pip3 install ansible molecule molecule-plugins[docker] docker

    # - name: Run Molecule tests.
    #   run: molecule test
    #   env:
    #     PY_COLORS: '1'
    #     ANSIBLE_FORCE_COLOR: '1'
    #     MOLECULE_DISTRO: ubuntu2204
    #     # - name: molecule

      #   uses: robertdebock/molecule-action@4.0.7
      #   with:
      #     image: ubuntu
