---
name: Molecule test
on:
  push:
    paths:
      - defaults/**
      - handlers/**
      - meta/**
      - molecule/**
      - tasks/**
      - templates/**
      - vars/**
      - .github/workflows/molecule.yml
    branches:
      - develop
      - master
  pull_request:
    paths:
      - defaults/**
      - handlers/**
      - meta/**
      - molecule/**
      - tasks/**
      - templates/**
      - vars/**
      - .github/workflows/molecule.yml
    branches:
      - develop
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.8
        with:
          image: ubuntu
